/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

// Your description goes here...

#include "RooMyPdf.h"

#include <RooAbsReal.h>
#include <RooAbsCategory.h>

#include <Riostream.h>
#include <TMath.h>

#include <cmath>
#include "RooMath.h"
#include "TMath.h"

#include "TError.h"

ClassImp(RooMyPdf);

RooMyPdf::RooMyPdf(const char *name, const char *title,
                        RooAbsReal& _m,
                        RooAbsReal& _m0,
                        RooAbsReal& _sigma,
                        RooAbsReal& _n,
                        RooAbsReal& _alpha,
                        RooAbsReal& _n2,
                        RooAbsReal& _alpha2)
   : RooAbsPdf(name,title),
   m("m","m",this,_m),
   m0("m0","m0",this,_m0),
   sigma("sigma","sigma",this,_sigma),
   n("n","n",this,_n),
   alpha("alpha","alpha",this,_alpha),
   n2("n2","n2",this,_n2),
   alpha2("alpha2","alpha2",this,_alpha2)
{
}

RooMyPdf::RooMyPdf(RooMyPdf const &other, const char *name)
   : RooAbsPdf(other,name),
   m("m",this,other.m),
   m0("m0",this,other.m0),
   sigma("sigma",this,other.sigma),
   n("n",this,other.n),
   alpha("alpha",this,other.alpha),
   n2("n2",this,other.n2),
   alpha2("alpha2",this,other.alpha2)
{
}

double RooMyPdf::ApproxErf(double arg) const
{
  static const double erflim = 5.0;
  if( arg > erflim )
    return 1.0;
  if( arg < -erflim )
    return -1.0;

  return RooMath::erf(arg);
}

double RooMyPdf::evaluate() const 
{
   return RooMyPdf_evaluate(m, m0, sigma, n, alpha, n2, alpha2); 
}

void RooMyPdf::computeBatch(double *output, std::size_t size, RooFit::Detail::DataMap const &dataMap) const 
{ 
   std::span<const double> mSpan = dataMap.at(m);
   std::span<const double> m0Span = dataMap.at(m0);
   std::span<const double> sigmaSpan = dataMap.at(sigma);
   std::span<const double> nSpan = dataMap.at(n);
   std::span<const double> alphaSpan = dataMap.at(alpha);
   std::span<const double> n2Span = dataMap.at(n2);
   std::span<const double> alpha2Span = dataMap.at(alpha2);

   for (std::size_t i = 0; i < size; ++i) {
      output[i] = RooMyPdf_evaluate(mSpan.size() > 1 ? mSpan[i] : mSpan[0],
                               m0Span.size() > 1 ? m0Span[i] : m0Span[0],
                               sigmaSpan.size() > 1 ? sigmaSpan[i] : sigmaSpan[0],
                               nSpan.size() > 1 ? nSpan[i] : nSpan[0],
                               alphaSpan.size() > 1 ? alphaSpan[i] : alphaSpan[0],
                               n2Span.size() > 1 ? n2Span[i] : n2Span[0],
                               alpha2Span.size() > 1 ? alpha2Span[i] : alpha2Span[0]);
   }
} 
void RooMyPdf::translate(RooFit::Detail::CodeSquashContext &ctx) const
{
   ctx.addResult(this, ctx.buildCall("RooMyPdf_evaluate", m, m0, sigma, n, alpha, n2, alpha2));
}
