/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef RooMyPdf_h
#define RooMyPdf_h

#include <RooAbsPdf.h>
#include <RooRealProxy.h>
#include <RooCategoryProxy.h>
#include <RooAbsReal.h>
#include <RooAbsCategory.h>

#include "RooMath.h"
#include "TMath.h"

#include "TError.h"
#include <complex>

class RooMyPdf : public RooAbsPdf {
public:
   RooMyPdf() {}
   RooMyPdf(const char *name, const char *title,        RooAbsReal& _m,
        RooAbsReal& _m0,
        RooAbsReal& _sigma,
        RooAbsReal& _n,
        RooAbsReal& _alpha,
        RooAbsReal& _n2,
        RooAbsReal& _alpha2);
  RooMyPdf(RooMyPdf const &other, const char *name=nullptr);
  TObject* clone(const char *newname) const override { return new RooMyPdf(*this, newname); }
protected:

  RooRealProxy m ;
  RooRealProxy m0 ;
  RooRealProxy sigma ;
  RooRealProxy n ;
  RooRealProxy alpha ;
  RooRealProxy n2 ;
  RooRealProxy alpha2 ;

  double ApproxErf(double arg) const;
  double evaluate() const override;
  void computeBatch(double* output, std::size_t size, RooFit::Detail::DataMap const&) const override;
  void translate(RooFit::Detail::CodeSquashContext &ctx) const override;

private:

  ClassDefOverride(RooMyPdf, 1) // Your description goes here...
};
inline double RooMyPdf_evaluate(double m, double m0, double sigma, double n, double alpha, double n2, double alpha2) 
{
  double t = (m-m0)/sigma;
  if (alpha < 0) t = -t;

  double absAlpha = fabs((double)alpha);
  double absAlpha2 = fabs((double)alpha2);

  if (t >= -absAlpha && t < absAlpha2) {
    return exp(-0.5*t*t);
  }
  if (t < -absAlpha) {
    double a = TMath::Power(n/absAlpha,n)*exp(-0.5*absAlpha*absAlpha);
    double b = n/absAlpha - absAlpha;
    return a/TMath::Power(b - t, n);
  }
  if (t >= absAlpha2) {
    double c = TMath::Power(n2/absAlpha2,n2)*exp(-0.5*absAlpha2*absAlpha2);
    double d = n2/absAlpha2 - absAlpha2;
    return c/TMath::Power(d + t, n2);
  }
  return 0.0;
}


#endif // RooMyPdf_h
