/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

// Your description goes here...

#include "Riostream.h"

#include "VWGPdfRatio.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include <math.h>
#include "TMath.h"

ClassImp(VWGPdfRatio);

 VWGPdfRatio::VWGPdfRatio(const char *name, const char *title,
                        RooAbsReal& _x,
                        RooAbsReal& _A,
                        RooAbsReal& _B,
                        RooAbsReal& _C,
                        RooAbsReal& _Afix,
                        RooAbsReal& _Bfix,
                        RooAbsReal& _Cfix,
			RooAbsReal& _kfix) :
   RooAbsPdf(name,title),
   x("x","x",this,_x),
   A("A","A",this,_A),
   B("B","B",this,_B),
   C("C","C",this,_C),
   Afix("Afix","Afix",this,_Afix),
   Bfix("Bfix","Bfix",this,_Bfix),
   Cfix("Cfix","Cfix",this,_Cfix),
   kfix("kfix","kfix",this,_kfix)
 {
 }


 VWGPdfRatio::VWGPdfRatio(const VWGPdfRatio& other, const char* name) :
   RooAbsPdf(other,name),
   x("x",this,other.x),
   A("A",this,other.A),
   B("B",this,other.B),
   C("C",this,other.C),
   Afix("Afix",this,other.Afix),
   Bfix("Bfix",this,other.Bfix),
   Cfix("Cfix",this,other.Cfix),
   kfix("kfix",this,other.kfix)
 {
 }

 Double_t VWGPdfRatio::evaluate() const
 {
    Double_t sigma = B + C * ((x - A) / A);
    Double_t sigmafix = Bfix + Cfix * ((x - Afix) / Afix);
    Double_t num = TMath::Exp(-(x - A) * (x - A)/(2. * sigma * sigma));
    Double_t den = TMath::Exp(-(x - Afix) * (x - Afix)/(2. * sigmafix * sigmafix)) + kfix;
    return num/den;
 }
