/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef VWGPDFRATIO
#define VWGPDFRATIO

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class VWGPdfRatio : public RooAbsPdf {
public:
  VWGPdfRatio() {} ;
  VWGPdfRatio(const char *name, const char *title,
	    RooAbsReal& _x,
	    RooAbsReal& _A,
	    RooAbsReal& _B,
            RooAbsReal& _C, 
	    RooAbsReal& _Afix,
	    RooAbsReal& _Bfix,
            RooAbsReal& _Cfix, 
	    RooAbsReal& _kfix);
  VWGPdfRatio(const VWGPdfRatio& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new VWGPdfRatio(*this,newname); }
  inline virtual ~VWGPdfRatio() { }

protected:

  RooRealProxy x ;
  RooRealProxy A ;
  RooRealProxy B ;
  RooRealProxy C ;
  RooRealProxy Afix ;
  RooRealProxy Bfix ;
  RooRealProxy Cfix ;
  RooRealProxy kfix ;

  Double_t evaluate() const ;

private:

  ClassDef(VWGPdfRatio,1) // Your description goes here...
};

#endif
