/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

// Your description goes here...

#include "Riostream.h"

#include "VWGPdfK.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include <math.h>
#include "TMath.h"

ClassImp(VWGPdfK);

 VWGPdfK::VWGPdfK(const char *name, const char *title,
                        RooAbsReal& _x,
                        RooAbsReal& _A,
                        RooAbsReal& _B,
                        RooAbsReal& _C,
			RooAbsReal& _k) :
   RooAbsPdf(name,title),
   x("x","x",this,_x),
   A("A","A",this,_A),
   B("B","B",this,_B),
   C("C","C",this,_C),
   k("k","k",this,_k)
 {
 }


 VWGPdfK::VWGPdfK(const VWGPdfK& other, const char* name) :
   RooAbsPdf(other,name),
   x("x",this,other.x),
   A("A",this,other.A),
   B("B",this,other.B),
   k("k",this,other.k),
   C("C",this,other.C)
 {
 }

 Double_t VWGPdfK::evaluate() const
 {
    Double_t sigma = B + C * ((x - A) / A);
    return TMath::Exp(-(x - A) * (x - A)/(2. * sigma * sigma)) + k;
 }
