/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef VWGPDFK
#define VWGPDFK

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class VWGPdfK : public RooAbsPdf {
public:
  VWGPdfK() {} ;
  VWGPdfK(const char *name, const char *title,
	    RooAbsReal& _x,
	    RooAbsReal& _A,
	    RooAbsReal& _B,
        RooAbsReal& _C, 
	RooAbsReal& _k);
  VWGPdfK(const VWGPdfK& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new VWGPdfK(*this,newname); }
  inline virtual ~VWGPdfK() { }

protected:

  RooRealProxy x ;
  RooRealProxy A ;
  RooRealProxy B ;
  RooRealProxy C ;
  RooRealProxy k ;

  Double_t evaluate() const ;

private:

  ClassDef(VWGPdfK,1) // Your description goes here...
};

#endif
